apiVersion: notification.halo.run/v1alpha1
kind: NotifierDescriptor
metadata:
  name: default-email-notifier
spec:
  displayName: 'Email Notification'
  description: 'Send notification to user via email'
  notifierExtName: 'halo-email-notifier'
  senderSettingRef:
    name: 'notifier-setting-for-email'
    group: 'sender'
---
apiVersion: v1alpha1
kind: Setting
metadata:
  name: notifier-setting-for-email
spec:
  forms:
    - group: sender
      label: Shipping settings
      formSchema:
        - $formkit: checkbox
          label: "Enable email notifier"
          value: false
          name: enable
        - $formkit: text
          if: "$enable"
          label: "username"
          name: username
          validation: required
        - $formkit: password
          if: "$enable"
          label: "password"
          name: password
          validation: required
        - $formkit: text
          if: "$enable"
          label: "display name"
          name: displayName
        - $formkit: text
          if: "$enable"
          label: "SMTP server address"
          name: host
          validation: required
        - $formkit: text
          if: "$enable"
          label: "port"
          name: port
          validation: required
        - $formkit: select
          if: "$enable"
          label: "encryption"
          name: encryption
          value: "SSL"
          options:
            - label: "SSL"
              value: "SSL"
            - label: "TLS"
              value: "TLS"
            - label: "No encryption"
              value: "NONE"
---
apiVersion: notification.halo.run/v1alpha1
kind: ReasonType
metadata:
  name: new-comment-on-post
spec:
  displayName: "My article recieved new comments"
  description: "If a reader leaves a new comment below your article, you will receive a notification telling you that there is a new comment. This notification event can help you keep abreast of readers' feedback on your articles so that you can better interact with readers and improve the quality and popularity of your articles."
  properties:
    - name: postName
      type: string
      description: "The name of the post."
    - name: postTitle
      type: string
    - name: postUrl
      type: string
    - name: commenter
      type: string
      description: "The display name of the commenter."
    - name: commentName
      type: string
      description: "The name of the comment."
    - name: content
      type: string
      description: "The content of the comment."
---
apiVersion: notification.halo.run/v1alpha1
kind: ReasonType
metadata:
  name: new-comment-on-single-page
spec:
  displayName: "My custom page received new comments"
  description: "When a custom page you create receives a new comment, you will receive a notification letting you know there is a new comment."
  properties:
    - name: pageName
      type: string
      description: "The name of the single page."
    - name: pageTitle
      type: string
    - name: pageUrl
      type: string
    - name: commenter
      type: string
      description: "The display name of the commenter."
    - name: commentName
      type: string
      description: "The name of the comment."
    - name: content
      type: string
      description: "The content of the comment."
---
apiVersion: notification.halo.run/v1alpha1
kind: ReasonType
metadata:
  name: someone-replied-to-you
spec:
  displayName: "Someone replied to me"
  description: "If another user replies to your comment, you will receive a notification letting you know that someone has replied to you."
  properties:
    - name: commentName
      type: string
      description: "The name of the comment."
    - name: commentSubjectTitle
      type: string
    - name: commentSubjectUrl
      type: string
    - name: quoteContent
      type: string
      optional: true
      description: "The content of quoted reply."
    - name: isQuoteReply
      type: boolean
    - name: commentContent
      type: string
    - name: replier
      type: string
      description: "The display name of the replier."
    - name: replyName
      type: string
      description: "The name of the reply."
    - name: content
      type: string
      description: "The content of the reply."
