apiVersion: notification.halo.run/v1alpha1
kind: NotificationTemplate
metadata:
  name: template-new-comment-on-post
spec:
  reasonSelector:
    reasonType: new-comment-on-post
    language: default
  template:
    title: "[(${commenter})] commented on your article《[(${postTitle})]》"
    rawBody: |
      [(${subscriber.displayName})] Hello：

        [(${commenter})] commented on your article《[(${postTitle})]》，The following is the specific content of the comments：

        [(${content})]
    htmlBody: |
      <div class="notification-content">
        <div class="head">
          <p class="honorific" th:text="|${subscriber.displayName} Hello：|"></p>
        </div>
        <div class="body">
          <p>
            <span th:text="${commenter}"></span> commented on your article
            <a th:href="${postUrl}" target="_blank" th:text="|《${postTitle}》|"></a>
            <span>，The following is the specific content of the comments：</span>
          </p>
          <pre class="content" th:text="${content}"></pre>
        </div>
        <div></div>
      </div>

---
apiVersion: notification.halo.run/v1alpha1
kind: NotificationTemplate
metadata:
  name: template-new-comment-on-single-page
spec:
  reasonSelector:
    reasonType: new-comment-on-single-page
    language: default
  template:
    title: "[(${commenter})] commented on your page《[(${pageTitle})]》"
    rawBody: |
      [(${subscriber.displayName})] Hello：

        [(${commenter})] commented on your page《[(${pageTitle})]》，The following is the specific content of the comments：

        [(${content})]
    htmlBody: |
      <div class="notification-content">
        <div class="head">
          <p class="honorific" th:text="|${subscriber.displayName} Hello：|"></p>
        </div>
        <div class="body">
          <p>
            <span th:text="${commenter}"></span>commented on your page
            <a th:href="${pageUrl}" target="_blank" th:text="|《${pageTitle}》|"></a>
            <span>，The following is the specific content of the comments：</span>
          </p>
          <pre class="content" th:text="${content}"></pre>
        </div>
        <div></div>
      </div>

---
apiVersion: notification.halo.run/v1alpha1
kind: NotificationTemplate
metadata:
  name: template-someone-replied-to-you
spec:
  reasonSelector:
    reasonType: someone-replied-to-you
    language: default
  template:
    title: "[(${replier})] Replied you in the comments
    rawBody: |
      [(${subscriber.displayName})] Hello：

        [(${replier})] in comments “[(${isQuoteReply ? quoteContent : commentContent})]” I replied to you. The following is the specific content of the reply：

        [(${content})]
    htmlBody: |
      <div class="notification-content">
        <div class="head">
          <p class="honorific" th:text="|${subscriber.displayName} Hello：|"></p>
        </div>
        <div class="body">
          <p>
            <span th:text="${replier}"></span> in comments 
            <a
              th:href="${commentSubjectUrl}"
              target="_blank"
              th:text="|”${isQuoteReply ? quoteContent : commentContent}”|"
            ></a>
            <span>I replied to you. The following is the specific content of the reply：</span>
          </p>
          <pre class="content" th:text="${content}"></pre>
        </div>
        <div></div>
      </div>
