apiVersion: v1alpha1
kind: Setting
metadata:
  name: system
spec:
  forms:
    - group: basic
      label: basic settings
      formSchema:
        - $formkit: text
          label: "site title"
          name: title
          validation: required
        - $formkit: text
          label: "Site subtitle"
          name: subtitle
        - $formkit: attachment
          label: Logo
          name: logo
          accepts:
            - 'image/*'
        - $formkit: attachment
          label: Favicon
          name: favicon
          accepts:
            - 'image/*'
    - group: post
      label: Article settings
      formSchema:
        - $formkit: number
          label: "Article list display number"
          name: postPageSize
          value: 10
          min: 1
          max: 100
          validation: required | max:100
        - $formkit: number
          label: "The number of articles displayed on the archive page"
          name: archivePageSize
          value: 10
          min: 1
          max: 100
          validation: required | max:100
        - $formkit: number
          label: "The number of articles displayed on the category page"
          name: categoryPageSize
          value: 10
          min: 1
          max: 100
          validation: required | max:100
        - $formkit: number
          label: "The number of articles displayed on the tab page"
          name: tagPageSize
          value: 10
          min: 1
          max: 100
          validation: required
        - $formkit: select
          label: "Alias generation strategy"
          name: slugGenerationStrategy
          value: 'generateByTitle'
          options:
            - label: 'According to the title'
              value: 'generateByTitle'
            - label: 'Timestamp'
              value: 'timestamp'
            - label: 'Short UUID'
              value: 'shortUUID'
            - label: 'UUID'
              value: 'UUID'
    - group: seo
      label: SEO set up
      formSchema:
        - $formkit: checkbox
          name: blockSpiders
          label: "Block search engines"
          value: false
        - $formkit: textarea
          name: keywords
          label: "Site keywords"
        - $formkit: textarea
          name: description
          label: "site description"
    - group: user
      label: user settings
      formSchema:
        - $formkit: checkbox
          name: allowRegistration
          label: "Open registration"
          value: false
        - $formkit: roleSelect
          name: defaultRole
          label: "Default role"
        - $formkit: attachmentPolicySelect
          name: avatarPolicy
          label: "Avatar storage location"
          value: "default-policy"
    - group: comment
      label: Comment settings
      formSchema:
        - $formkit: checkbox
          name: enable
          value: true
          label: "Enable comments"
        - $formkit: checkbox
          name: requireReviewForNew
          value: true
          label: "New comment moderation"
        - $formkit: checkbox
          name: systemUserOnly
          value: true
          label: "Only registered users are allowed to comment"
    - group: routeRules
      label: Topic routing settings
      formSchema:
        - $formkit: text
          label: "Category page routing prefix"
          value: "categories"
          name: categories
          validation: required | alphanumeric
        - $formkit: text
          label: "Tab routing prefix"
          value: "tags"
          name: tags
          validation: required | alphanumeric
        - $formkit: text
          label: "Archive page routing prefix"
          value: "archives"
          name: archives
          validation: required | alphanumeric
        - $formkit: select
          label: Article details page access rules
          value: '/archives/{slug}'
          options:
            - label: '/archives/{slug}'
              value: '/archives/{slug}'
            - label: '/archives/{name}'
              value: '/archives/{name}'
            - label: '/?p={name}'
              value: '/?p={name}'
            - label: '/?p={slug}'
              value: '/?p={slug}'
            - label: '/{year}/{slug}'
              value: '/{year:\d{4}}/{slug}'
            - label: '/{year}/{month}/{slug}'
              value: '/{year:\d{4}}/{month:\d{2}}/{slug}'
            - label: '/{year}/{month}/{day}/{slug}'
              value: '/{year:\d{4}}/{month:\d{2}}/{day:\d{2}}/{slug}'
          name: post
          validation: required
    - group: codeInjection
      label: code injection
      formSchema:
        - $formkit: code
          language: html
          height: 200px
          label: "overall situation head Label"
          name: globalHead
          help: "Inject code into the head tag section of all pages"
        - $formkit: code
          language: html
          height: 200px
          label: "head"
          name: contentHead
          help: "Inject code into the head tag section of article pages and custom pages"
        - $formkit: code
          language: html
          height: 200px
          label: "footer"
          name: footer
          help: "Inject code into the footer of all pages"
